Add UpSampling layers
JetBrains/KotlinDL pull request #146
Opened 2021-06-21 16:46 UTC by mkaze

Resolves #143. This PR adds an abstract base class for UpSampling layers and implements UpSampling1D, UpSampling2D and UpSampling3D layers.

- [x] Implement abstract base class for UpSampling layers.
- [x] Implement `UpSampling1D` layer class.
- [x] Implement `UpSampling2D` layer class.
- [x] Implement `UpSampling3D` layer class.
- [x] Add support for exporting layers' config to JSON.
- [x] Add support for importing layers from their JSON config.
- [ ] Add unit tests for all cropping layers (TODO; waiting for status of #103)

2021-06-24 05:25 UTC, mkaze commented
@zaleslaw This PR is ready to be reviewed.

2021-06-24 13:43 UTC, zaleslaw requested changes
So, what implementation did you use as a reference? The internals of Keras seems different...

2021-06-24 13:43 UTC, zaleslaw commented on api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/layer/reshaping/AbstractUpSampling.kt
> +public enum class InterpolationMethod(internal val methodName: String) {
Add KDocs

2021-06-24 13:43 UTC, zaleslaw commented on api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/layer/reshaping/AbstractUpSampling.kt
> +public abstract class AbstractUpSampling(
Add KDocs for the class and for fields

2021-06-24 13:43 UTC, zaleslaw commented on api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/layer/reshaping/AbstractUpSampling.kt
> +public fun repeat(tf: Ops, value: Operand<Float>, repeats: Int, axis: Int): Operand<Float> {
add KDocs

2021-06-24 13:43 UTC, zaleslaw commented on api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/layer/reshaping/AbstractUpSampling.kt
> +public fun repeat(tf: Ops, value: Operand<Float>, repeats: Int, axis: Int): Operand<Float> {
Maybe it should be protected or internal

2021-06-24 13:43 UTC, zaleslaw commented on api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/layer/reshaping/UpSampling2D.kt
> +            InterpolationMethod.NEAREST -> tf.image.resizeNearestNeighbor(input, newSize)
Really strange that UpSampling layers have so different implementations and level of interpolation usage

2021-06-25 03:15 UTC, mkaze commented
@zaleslaw Well, I used Keras implementation as reference. The implementation for 2D layer is the same (i.e. both Keras and my implementation use low-level image resizing methods). For the 1D and 3D layers, Keras defines a helper function for repeating the elements of a tensor along a specific axis and then use it to implement those layers. 

I also did the same (though, my implementation of the repeat function is a little bit different but the overall strategy is exactly the same) and used the repeat function in implementation of 3D layer; however, I didn't use it for 1D layer and instead opted to use the resize method of images for 1D layer as well (because basically you can view a 1D data as a 2D data as well). 

Personally, I don't think there is anything confusing about this, but anyways I can change the implementation of 1D layer to use the repeat function instead if that makes it more clear.

2021-06-25 03:54 UTC, mkaze commented
@zaleslaw The docs were improved and implementation of 1D layer was refactored to use the `repeats` helper function instead of image resizing approach.

2021-06-25 04:04 UTC, mkaze commented
@zaleslaw I decided to remove the redundant `computeUpSampledShape` method and directly use `computeOutputShape` instead.

2021-07-28 13:05 UTC, zaleslaw commented
Great PR and tests!

2021-07-28 13:05 UTC, merged