Added Mish Activation Function
JetBrains/KotlinDL pull request #173
Opened 2021-07-30 01:31 UTC by digantamisra98

Resolves [168](https://github.com/JetBrains/KotlinDL/issues/168)

2021-07-30 21:18 UTC, digantamisra98 commented
@zaleslaw This is ready for review.

2021-08-03 10:07 UTC, zaleslaw commented
Many thanks for the contribution, @digantamisra98 I'll run the TC and merge it if it is successful

2021-08-03 10:46 UTC, zaleslaw commented on api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/activation/Activations.kt
>      Swish;
; -> , due to enum in Kotlin https://kotlinlang.org/docs/enum-classes.html

2021-08-03 10:47 UTC, zaleslaw requested changes
Did you compile the Kotlin code or just added rows in the Notepad++? Because the code could not be compiled on TC servers

```
  > Task :api:compileKotlin
13:45:25   :api:compileKotlin
13:45:47     e: /mnt/agent/work/c1e3495e9fda7093/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/activation/Activations.kt: (234, 5): Expecting member declaration
13:45:47     e: /mnt/agent/work/c1e3495e9fda7093/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/activation/Activations.kt: (234, 5): Expecting member declaration
13:45:47     e: /mnt/agent/work/c1e3495e9fda7093/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/activation/Activations.kt: (258, 17): Unresolved reference: Mish
13:45:47     e: /mnt/agent/work/c1e3495e9fda7093/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/activation/Activations.kt: (258, 17): Unresolved reference: Mish
13:45:47     e: /mnt/agent/work/c1e3495e9fda7093/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelLoader.kt: (430, 9): Unresolved reference: ACTIVATION_MISH
13:45:47     e: /mnt/agent/work/c1e3495e9fda7093/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelLoader.kt: (430, 40): Unresolved reference: Mish
13:45:47     e: /mnt/agent/work/c1e3495e9fda7093/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelSaver.kt: (270, 21): Unresolved reference: Mish
13:45:47     e: /mnt/agent/work/c1e3495e9fda7093/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelLoader.kt: (430, 9): Unresolved reference: ACTIVATION_MISH
13:45:47     e: /mnt/agent/work/c1e3495e9fda7093/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelSaver.kt: (270, 29): Unresolved reference: ACTIVATION_MISH
13:45:47     
13:45:47     e: /mnt/agent/work/c1e3495e9fda7093/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelLoader.kt: (430, 40): Unresolved reference: Mish
13:45:47     e: /mnt/agent/work/c1e3495e9fda7093/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelSaver.kt: (270, 21): Unresolved reference: Mish
13:45:47     e: /mnt/agent/work/c1e3495e9fda7093/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelSaver.kt: (270, 29): Unresolved reference: ACTIVATION_MISH
13:45:47   > Task :api:compileKotlin FAILED
```

2021-08-03 15:24 UTC, zaleslaw commented
```
:api:compileKotlin
18:15:27     e: /mnt/agent/work/c1e3495e9fda7093/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelLoader.kt: (430, 9): Unresolved reference: ACTIVATION_MISH
18:15:27     e: /mnt/agent/work/c1e3495e9fda7093/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelSaver.kt: (270, 29): Unresolved reference: ACTIVATION_MISH
18:15:27     
18:15:27     e: /mnt/agent/work/c1e3495e9fda7093/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelLoader.kt: (430, 9): Unresolved reference: ACTIVATION_MISH
18:15:27     e: /mnt/agent/work/c1e3495e9fda7093/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelSaver.kt: (270, 29): Unresolved reference: ACTIVATION_MISH
```

Not compiled again, ok, I'll help to finish this request, clone your branch tomorrow and resolve the issue.

2021-08-03 15:33 UTC, mkaze commented
@digantamisra98 Just add the following line to the `KerasConstants.kt` file:

```kotlin
internal const val ACTIVATION_MISH: String = "mish"
```

2021-08-03 15:44 UTC, digantamisra98 commented
@mkaze Done, thanks. Had missed that out.

@zaleslaw Fixed the issues and yes I had just edited/ added the files in an IDE, I didn't build it locally. I hope it compiles now.

2021-08-04 09:01 UTC, merged

2021-08-04 09:03 UTC, zaleslaw commented
Thanks, @digantamisra98, for the contribution and @mkaze for the advice!
Good luck with ML science, and we will wait for new papers and results which could be implemented in DL frameworks and useful for the AutoML!